

export const APP_COLORS = {
  primary: 'bg-pink-400',
  primaryHover: 'hover:bg-pink-500',
  secondary: 'bg-sky-300',
  accent: 'text-pink-500',
  background: 'bg-pink-50',
  card: 'bg-white/80',
};

export const TRANSLATIONS = {
    en: {
        day: "DAY",
        focusMode: "Focus Mode",
        timeBudget: "Time Budget",
        learningMissions: "Learning Missions",
        dailyCompletion: "Daily Completion",
        trainingLog: "Training Log",
        edit: "Edit",
        preview: "Preview",
        completeDay: "COMPLETE DAY",
        syncing: "SYNCING...",
        missionClear: "MISSION CLEAR!",
        mins: "mins",
        aiCheck: "AI Check",
        verified: "Verified!",
        typeAnswer: "Type your answer...",
        senseiAsks: "Sensei asks:",
        myJourney: "My Learning Journey",
        completion: "Completion",
        daysStreak: "Days Streak",
        timeInvested: "Time Invested",
        totalPlan: "Total Plan",
        taskHistory: "Task Completion History",
        topicsCovered: "Topics Covered",
        masterPlan: "Master Plan",
        roadToMastery: "Your road to mastery",
        missions: "Missions",
        inProgress: "IN PROGRESS",
        generatePlan: "GENERATE PLAN",
        calibrating: "Calibrating Curriculum...",
        consulting: "Consulting AI Sensei",
        today: "Today",
        roadmap: "Roadmap",
        stats: "Stats",
        introTitle: "ANILEARN",
        introSubtitle: "Protocol: Select Mission",
        introDesc: "Choose an existing protocol or initialize a new training sequence.",
        placeholderLog: "// Log your findings here (Markdown supported)...",
        newProtocol: "New Protocol",
        protocols: "Protocols",
        create: "Create",
        learningTopic: "Learning Topic",
        contextDetails: "Requirements / Context",
        newProtocolDesc: "Define your target. AI Sensei will construct the path.",
        initialize: "Initialize Protocol",
        resume: "RESUME TRAINING",
        noPlans: "No active protocols. Create one to begin."
    },
    zh: {
        day: "第",
        focusMode: "专注模式",
        timeBudget: "时间预算",
        learningMissions: "学习任务",
        dailyCompletion: "今日进度",
        trainingLog: "训练日志",
        edit: "编辑",
        preview: "预览",
        completeDay: "完成今日",
        syncing: "同步中...",
        missionClear: "任务完成！",
        mins: "分钟",
        aiCheck: "AI 检查",
        verified: "已通过！",
        typeAnswer: "输入你的答案...",
        senseiAsks: "老师提问：",
        myJourney: "我的学习之旅",
        completion: "完成度",
        daysStreak: "连续打卡",
        timeInvested: "投入时间",
        totalPlan: "总计划",
        taskHistory: "任务完成历史",
        topicsCovered: "已学主题",
        masterPlan: "大师计划",
        roadToMastery: "通往大师之路",
        missions: "个任务",
        inProgress: "进行中",
        generatePlan: "生成计划",
        calibrating: "正在校准课程...",
        consulting: "正在咨询 AI 老师",
        today: "今日",
        roadmap: "路线图",
        stats: "统计",
        introTitle: "ANILEARN",
        introSubtitle: "协议：选择任务",
        introDesc: "选择现有协议或启动新的训练序列。",
        placeholderLog: "// 在此记录你的发现 (支持 Markdown)...",
        newProtocol: "新协议",
        protocols: "协议列表",
        create: "创建",
        learningTopic: "学习主题",
        contextDetails: "要求 / 背景",
        newProtocolDesc: "定义你的目标。AI 老师将为你构建路径。",
        initialize: "启动协议",
        resume: "继续训练",
        noPlans: "暂无活跃协议。请创建一个以开始。"
    }
};
