

export const APP_COLORS = {
  primary: 'bg-pink-400',
  primaryHover: 'hover:bg-pink-500',
  secondary: 'bg-sky-300',
  accent: 'text-pink-500',
  background: 'bg-pink-50',
  card: 'bg-white/80',
};

// ZZZ Cidd Concept Art or similar tech/anime vibe
export const SPLASH_IMAGE = "https://image.civitai.com/xG1nkqKTMzGDvpLkqFT7WA/69289a16-3d3f-436b-8933-c28296d79a7b/width=450/00006-3225086703.jpeg";

export const TRANSLATIONS = {
    en: {
        day: "Day",
        focusMode: "Focus",
        timeBudget: "Budget",
        learningMissions: "Missions",
        dailyCompletion: "Progress",
        trainingLog: "Log",
        edit: "Edit",
        preview: "Preview",
        completeDay: "Complete",
        syncing: "Syncing...",
        missionClear: "CLEAR!",
        mins: "m",
        aiCheck: "Check",
        verified: "OK",
        typeAnswer: "Answer...",
        senseiAsks: "Sensei:",
        myJourney: "Journey",
        completion: "Done",
        daysStreak: "Streak",
        timeInvested: "Hours",
        totalPlan: "Total",
        taskHistory: "History",
        topicsCovered: "Topics",
        masterPlan: "Plan",
        roadToMastery: "Roadmap",
        missions: "Tasks",
        inProgress: "Active",
        generatePlan: "Generate",
        calibrating: "Calibrating...",
        consulting: "Thinking...",
        today: "Today",
        roadmap: "Plan",
        stats: "Stats",
        introTitle: "ANILEARN",
        introSubtitle: "Protocol Init",
        introDesc: "Select a mission.",
        placeholderLog: "// Notes...",
        newProtocol: "New Protocol",
        protocols: "Protocols",
        create: "Create",
        learningTopic: "Topic",
        contextDetails: "Context",
        newProtocolDesc: "Target definition.",
        initialize: "Start",
        resume: "Resume",
        noPlans: "No protocols found.",
        menu: "Menu",
        settings: "Settings",
        switchTheme: "Theme",
        switchLang: "Language"
    },
    zh: {
        day: "Day",
        focusMode: "专注",
        timeBudget: "预算",
        learningMissions: "任务",
        dailyCompletion: "进度",
        trainingLog: "日志",
        edit: "编辑",
        preview: "预览",
        completeDay: "完成",
        syncing: "同步...",
        missionClear: "完成！",
        mins: "分",
        aiCheck: "检查",
        verified: "通过",
        typeAnswer: "回答...",
        senseiAsks: "提问：",
        myJourney: "旅程",
        completion: "完成度",
        daysStreak: "连胜",
        timeInvested: "时长",
        totalPlan: "总计",
        taskHistory: "历史",
        topicsCovered: "主题",
        masterPlan: "计划",
        roadToMastery: "路线图",
        missions: "任务",
        inProgress: "进行中",
        generatePlan: "生成",
        calibrating: "校准中...",
        consulting: "思考中...",
        today: "今日",
        roadmap: "计划",
        stats: "统计",
        introTitle: "ANILEARN",
        introSubtitle: "协议启动",
        introDesc: "选择任务。",
        placeholderLog: "// 记录...",
        newProtocol: "新协议",
        protocols: "协议列表",
        create: "创建",
        learningTopic: "主题",
        contextDetails: "背景",
        newProtocolDesc: "定义目标。",
        initialize: "启动",
        resume: "继续",
        noPlans: "无协议。",
        menu: "菜单",
        settings: "设置",
        switchTheme: "主题",
        switchLang: "语言"
    }
};