
export enum LearningStatus {
  LOCKED = 'LOCKED',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED'
}

export type Language = 'en' | 'zh';
export type Theme = 'light' | 'dark';

export interface TaskLink {
  label: string;
  url: string;
}

export interface Task {
  id: string;
  description: string;
  isCompleted: boolean;
  estimatedMinutes: number;
  links?: TaskLink[]; 
  verificationQuestion?: string; 
  answerKey?: string; // The correct answer generated by AI upfront
  userAnswer?: string; // User's self-input
  isVerified?: boolean; // If user marked it as correct
}

export interface LearningDay {
  dayNumber: number;
  topic: string;
  summary: string;
  tasks: Task[];
  status: LearningStatus;
  userNotes?: string;
  completionDate?: string;
  mood?: 'happy' | 'neutral' | 'tired' | 'confused';
}

export interface LearningPlanMetadata {
  id: string;
  title: string;
  topic: string;
  totalDays: number;
  createdAt: string;
  progress: number; // 0-100
}

export interface LearningPlan extends LearningPlanMetadata {
  days: LearningDay[];
  context?: string;
}

export interface ExtensionResource {
  title: string;
  description: string;
  url: string; // Can be a search term if real URL is hard to guess
}

export interface DailyRecap {
  summary: string;
  extensions: ExtensionResource[];
}
